name: Deploy self host

on:
  push:
    branches: [dev]

jobs:
  greeting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      # 签出代码
      - name: Check out repository code
        uses: actions/checkout@v2
        # 安装依赖
      - name: Install dependencies
        run: npm ci

      - name: SCP-Deploy
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "tests/a.txt,tests/b.txt"
          target: "/docker_volumes/nginx/sites/babel-ast-explorer"
