name: Deploy self host

on:
  push:
    branches: [dev]

jobs:
  greeting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      # 签出代码
      - name: Check out repository code
        uses: actions/checkout@v2
      # 安装依赖
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      # 构建
      - name: Build Project
        run: npm run build
        
      # scp 上传
      - name: SCP-Deploy
        run: 'cd ./build/'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./"
          target: "/docker_volumes/nginx/sites/tools/babel-ast-explorer"
          debug: true
